lins_alert/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'app.views.index', name='index'),
	url(r'^settings/$', 'app.views.settings', name='settings'),
	url(r'^contacts/$', 'app.views.contacts', name='contacts'),
	url(r'^sign_in/$', 'app.views.signIn', name='signIn'),
	url(r'^sign_up/$', 'app.views.signUp', name='signUp'),
	url(r'^sign_in_vk/$', 'app.views.signInVk', name='signInVk'),
	url(r'^sign_out/$', 'app.views.signOut', name='signOut'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

app/forms.py
# -*- coding: utf-8 -*-

from django.contrib.auth import authenticate
from django.contrib.auth.models import User
import floppyforms as forms
from models import Alert

RU_ERRORS = {
	'required': u'Заполните поле',
	'invalid': u'Проверьте корретность введенных данных'
}

class SignUpForm(forms.Form):
	username = forms.CharField(error_messages=RU_ERRORS, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u'Логин', 'autofocus': ''}))
	password = forms.CharField(error_messages=RU_ERRORS, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': u'Пароль'}))
	password_repeat = forms.CharField(error_messages=RU_ERRORS, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': u'Повторите пароль'}))

	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()

		password = cleaned_data.get('password')
		password_repeat = cleaned_data.get('password_repeat')

		if password != password_repeat:
			raise forms.ValidationError(u'Пароли не совпадают')

		return cleaned_data

	def clean_username(self):
		username = self.cleaned_data['username']

		if User.objects.filter(username=username).count() != 0:
			raise forms.ValidationError(u'Пользователь с таким логином уже существует')

		return self.cleaned_data

class SignInForm(forms.Form):
	username = forms.CharField(error_messages=RU_ERRORS, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u'Логин', 'autofocus': ''}))
	password = forms.CharField(error_messages=RU_ERRORS, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': u'Пароль'}))

	def clean(self):
		cleaned_data = super(SignInForm, self).clean()

		if not self.errors:
			user = authenticate(username=cleaned_data.get('username'), password=cleaned_data.get('password'))
			if user is None:
				raise forms.ValidationError(u'Пользователя с таким логином или паролем не существует')
			self.user = user
	
		return cleaned_data

	def get_user(self):
		return self.user or None

class SettingsForm(forms.ModelForm):
	start = forms.DateField(input_formats=('%d.%m.%Y',), error_messages=RU_ERRORS, widget=forms.DateInput(attrs={'class': 'input-small form-control'}))
	finish = forms.DateField(input_formats=('%d.%m.%Y',), error_messages=RU_ERRORS, widget=forms.DateInput(attrs={'class': 'input-small form-control'}))
	time = forms.TimeField(input_formats=('%H:%M',), error_messages=RU_ERRORS, widget=forms.TimeInput(attrs={'class': 'form-control', 'id': 'alert-time-display', 'value': '12:00'}))
	email = forms.EmailField(required=False, error_messages=RU_ERRORS, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': u'Укажите email для оповещений'}))
	phone = forms.RegexField(r'^\+79\d{9}$', '^\+79\d{9}$', required=False, error_messages=RU_ERRORS, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': u'+79123456789'}))
	user_time = forms.CharField(widget=forms.HiddenInput())

	class Meta:
		model = Alert
		widgets = {
			'alert_email': forms.CheckboxInput(attrs={'id': 'email-alert'}),
			'alert_sms': forms.CheckboxInput(attrs={'id': 'sms-alert'}),
			'period': forms.Select(attrs={'class': 'form-control'}),
		}
		exclude = ['user', 'alert_server_time']

	def clean(self):
		cleaned_data = super(SettingsForm, self).clean()

		if cleaned_data.get('alert_email') and cleaned_data.get('email') == '':
			raise forms.ValidationError(u'Введите email')

		if cleaned_data.get('alert_sms') and cleaned_data.get('phone') == '':
			raise forms.ValidationError(u'Введите номер телефона')
	
		return cleaned_data

class ContactForm(forms.Form):
	email = forms.CharField(error_messages=RU_ERRORS, widget=forms.EmailInput(attrs={'class': 'form-control'}))
	subject = forms.CharField(error_messages=RU_ERRORS, widget=forms.TextInput(attrs={'class': 'form-control'}))
	message = forms.CharField(error_messages=RU_ERRORS, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 7}))

app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		
		<!-- <link rel="shortcut icon" href="../../assets/ico/favicon.png"> -->

		<title>{% block title %}{% endblock %}</title>

		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<link href="/static/css/social-buttons.css" rel="stylesheet">
		<link href="/static/css/style.css" rel="stylesheet">
		{% block styles %}{% endblock %}

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
		{% block scripts %}{% endblock %}
	</head>
	<body>
		<div class="navbar-wrapper">
			<div class="container">
				<div class="navbar navbar-inverse navbar-default">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/">LinsAlert</a>
					</div>
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
							<li class="{% block main_page %}{% endblock %}"><a href="/">Главная</a></li>
							<li class="{% block contacts_page %}{% endblock %}"><a href="/contacts/">Контакты</a></li>
							{% if not user.is_authenticated %}
							<li class="{% block sign_up_page %}{% endblock %}"><a href="/sign_up/">Регистрация</a></li>
							<li class="{% block sign_in_page %}{% endblock %}"><a href="/sign_in/">Авторизация</a></li>
							{% endif %}
							{% if user.is_authenticated %}
							<li class="dropdown {% block settings_page %}{% endblock %}">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> {{ user.first_name }} <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><a href="/settings">Настройки <span class="glyphicon glyphicon-cog"></span></a></li>
									<li class="divider"></li>
									<li><a href="/sign_out">Выйти <span class="glyphicon glyphicon-log-out"></span></a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
		</div>

		{% block content %}{% endblock %}

		<div class="container">
			<hr class="featurette-divider">
			<footer>
				<p class="pull-right">
					<a class="link" href="#">Наверх <span class="glyphicon glyphicon-chevron-up"></span></a>
				</p>
				<p>&copy; 2013, <a class="link" href="mailto:shpuntik74@gmail.com">LinsAlert</a></p>
			</footer>
		</div>
  	</body>
</html>

app/templates/contacts.html
{% extends 'base.html' %}

{% block title%}
LinsAlert - Контакты
{% endblock %}

{% block contacts_page %}
active
{% endblock %}

{% block styles %}
<style>
	#disqus_thread {
		padding: 10px 20px;
		border: 1px solid #ccc;
		border-radius: 2px;
	}

	#layout #footer {
		display: none;
	}
</style>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
			{% if alert %}
			<div class="alert {{alert.cls}} alert-dismissable">
				<strong>{{ alert.txt }}</strong>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			</div>
			{% endif %}

			<form class="form" action="/contacts/" method="post">{% csrf_token %}
				<h2 class="form-sign-heading">Обратная связь</h2>
				{% if form.non_field_errors %}
					{% for error in form.non_field_errors %}
						<div class="alert alert-danger alert-dismissable">
							<strong>{{ error|escape }}</strong>
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						</div>
					{% endfor %}
				{% endif %}
				<div class="form-group">
					<label>Ваш email</label>
					{% if form.email.errors %}
						{% for error in form.email.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					{{ form.email }}
				</div>
				<div class="form-group">
					<label>Тема</label>
					{% if form.email.errors %}
						{% for error in form.email.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					{{ form.subject }}
				</div>
				<div class="form-group">
					<label>Текст сообщения</label>
					{% if form.email.errors %}
						{% for error in form.email.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					{{ form.message }}
				</div>
				<button class="btn btn-primary" type="sumbit">Отправить</button>
			</form>
		</div>
	</div>
	
	<div class="row">
		<div class="col-lg-6">
			<h2 class="form-sign-heading">Отзывы и предложения</h2>
			<div id="disqus_thread"></div>
			<script type="text/javascript">
				/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
				var disqus_shortname = 'linsalert'; // required: replace example with your forum shortname
				/* * * DON'T EDIT BELOW THIS LINE * * */
				(function() {
					var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
					dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
					(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
				})();
			</script>
			<noscript>Пожалуйста, включите JavaScript, чтобы увидеть комментарии</noscript>
		</div>
	</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title%}
LinsAlert
{% endblock %}

{% block main_page %}
active
{% endblock %}

{% block content %}
<div class="container">
	<div class="jumbotron">
		<div class="container">
			<h1>LinsAlert</h1>
			<p>Этот сервис создан для людей, которые пользуются контактными линзами. Благодаря LinsAlert вы не забудете сменить старую пару линз и сохраните свои глаза здоровыми.</p>
			<p class="transparent-btn">
				{% if not user.is_authenticated %}
				<a class="btn btn-info btn-small" href="/sign_in/">Войти &raquo;</a>
				<a class="btn btn-primary btn-small" href="/sign_up/">Регистрация &raquo;</a>
				{% endif %}
			</p>
		</div>
	</div>
</div>

<div class="container marketing">
	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading">Просто. <span class="text-muted">Всего 1 действие.</span></h2>
			<p class="lead">Всё что от вас требуется - установить время оповещния и вы никогда больше не забудете сменить контактные линзы.</p>
		</div>
		<div class="col-md-5">
			<img class="featurette-image img-responsive img-circle" src="/static/images/promo1.jpg" alt="">
		</div>
	</div>
			
	<hr class="featurette-divider">
			
	<div class="row featurette">
		<div class="col-md-5">
			<img class="featurette-image img-responsive img-circle" src="/static/images/500.png" alt="Generic placeholder image">
		</div>
		<div class="col-md-7">
			<h2 class="featurette-heading">Удобные оповещения. <span class="text-muted">С помощью email.</span></h2>
			<p class="lead">Большинство людей пользуются электронной почтой, поэтому сервис LinsAlert позволяет уведомлять вас через email - быстро и удобно.</p>
		</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading">Ещё удобнее! <span class="text-muted">С помощью sms.</span></h2>
			<p class="lead">Если вы не пользуетесь почтой или редко её проверяете, вы всё равно будете уведомлены, подлкючив sms-оповещения.</p>
		</div>
		<div class="col-md-5">
			<img class="featurette-image img-responsive img-circle" src="/static/images/500.png" alt="Generic placeholder image">
		</div>
	</div>
</div>
{% endblock %}

app/templates/settings.html
{% extends 'base.html' %}

{% block title%}
LinsAlert - Настройки
{% endblock %}

{% block settings_page %}
active
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="/static/css/bootstrap-datepicker.css" />
<style>
.email-alert-input, .sms-alert-input {
	margin-top: 10px;
}

.checkbox-inline {
	margin-right: 20px;
}

#alert-time-display {
	text-align: center;
	color: #333;
}
</style>
{% endblock %}

{% block scripts %}
<script src="/static/js/bootstrap-datepicker.js"></script>
<script src="/static/js/locales/bootstrap-datepicker.ru.js"></script>
<script>
$(document).ready(function(){

	/*
	*	DatePicker
	*/

	var now = new Date();
	var now_format = now.getDate() + "/" + parseInt(now.getMonth()+1) + "/" + now.getFullYear();

	$(".input-daterange").datepicker({
		format: "dd.mm.yyyy",
		startDate: now_format,
		endDate: "01/08/2014",
		language: "ru",
		orientation: "auto left",
		autoclose: true,
		todayHighlight: true
	});

	/*
	*	TimePicker
	*/

	var toggleTime = 0,	//0 - plus, 1 - minus
		curTime = $("#alert-time-display").val() || "12:00";

	function updateTime(){
		var display = $("#alert-time-display");
		var t = curTime.split(/:|-/),
			hour = t[0],
			min = t[1];

		if(hour > 23) hour = 0

		if(min == 0){
			min = 30;
			if(toggleTime && hour != 0) hour--;
			else if(toggleTime && hour == 0) hour = 23;
		}
		else{
			min = "00";
			if(!toggleTime && hour != 23) hour++;
			else if(!toggleTime && hour == 23) hour = 0;
		};

		curTime = hour + ":" + min;
		display.val(curTime);
	};

	$("#plus-time").click(function(){
		toggleTime = 0;
		curTime = $("#alert-time-display").val() || "12:00"
		updateTime();
	});

	$("#minus-time").click(function(){
		toggleTime = 1;
		curTime = $("#alert-time-display").val() || "12:00"
		updateTime();
	});

	/*
	*	Controls
	*/

	var email, phone;

	$("#email-alert").click(function(){
		if($(this).is(":checked")) $(".email-alert-input").show().find("input").val(email);
		else{
			email = $(".email-alert-input").find("input").val();
			$(".email-alert-input").hide().find("input").val("");
		};
	});

	$("#sms-alert").click(function(){
		if($(this).is(":checked")) $(".sms-alert-input").show().find("input").val(phone);
		else{
			phone = $(".sms-alert-input").find("input").val();
			$(".sms-alert-input").hide().find("input").val("");
		};
	});

	var now = new Date();

	$("#id_user_time").val(now.getHours());

});
</script>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			
			{% if alert %}
			<div class="alert {{alert.cls}} alert-dismissable">
				<strong>{{ alert.txt }}</strong>
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			</div>
			{% endif %}

			<form class="form" action="/settings/" method="post">{% csrf_token %}
				<h2 class="form-sign-heading">Настройки</h2>
				{% if form.non_field_errors %}
					{% for error in form.non_field_errors %}
						<div class="alert alert-danger alert-dismissable">
							<strong>{{ error|escape }}</strong>
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						</div>
					{% endfor %}
				{% endif %}
				<div class="form-group">
					<label>Способ оповещения</label>
					<div>
						<label class="checkbox-inline">
							{{ form.alert_email }} email
						</label>				
						<label class="checkbox-inline">
							{{ form.alert_sms }} sms
						</label>
					</div>
					<div class="email-alert-input" {% if not form.alert_email.value %}style="display: none;"{% endif %}>
						{% if form.email.errors %}
							{% for error in form.email.errors %}
								<div class="alert alert-danger alert-dismissable">
									<strong>{{ error|escape }}</strong>
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								</div>
							{% endfor %}
						{% endif %}
						<div class="input-group">
							<span class="input-group-addon" style="color: #333;">
								<span class="glyphicon glyphicon-envelope"></span>
							</span>
							{{ form.email }}
						</div>
					</div>
					<div class="sms-alert-input" {% if not form.alert_sms.value %}style="display: none;"{% endif %}>
						{% if form.phone.errors %}
							{% for error in form.phone.errors %}
								<div class="alert alert-danger alert-dismissable">
									<strong>{{ error|escape }}</strong>
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
								</div>
							{% endfor %}
						{% endif %}
						<div class="input-group">
							<span class="input-group-addon" style="color: #333;">
								<span class="glyphicon glyphicon-phone"></span>
							</span>
							{{ form.phone }}
						</div>
					</div>
				</div>
				<div class="form-group">
					<label>Период работы оповещений</label>
					{% if form.start.errors %}
						{% for error in form.start.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					{% if form.finish.errors %}
						{% for error in form.finish.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					<div class="input-daterange input-group" id="datepicker">
						<span class="input-group-addon" style="color: #333;">с</span>
						{{ form.start }}
						<span class="input-group-addon" style="color: #333;">по</span>
						{{ form.finish }}
					</div>
				</div>
				<div class="form-group">
					<label>Время оповещения</label>
					{% if form.time.errors %}
						{% for error in form.time.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					<div class="row">
						<div class="col-lg-6">
							<div class="input-group">
								<div class="input-group-btn">
									<button id="minus-time" type="button" class="btn btn-default"><span class="glyphicon glyphicon-minus"></span></button>
								</div>	
								{{ form.time }}					
								<div class="input-group-btn">
									<button id="plus-time" type="button" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span></button>							
								</div>				
							</div>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label>Частота оповещений</label>			
					{% if form.period.errors %}
						{% for error in form.period.errors %}
							<div class="alert alert-danger alert-dismissable">
								<strong>{{ error|escape }}</strong>
								<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							</div>
						{% endfor %}
					{% endif %}
					<div class="input-group">
						{{ form.period }}
					</div>
				</div>
				{{ form.user_time }}
				<button class="btn btn-primary" type="sumbit">Сохранить</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

app/templates/sign_in.html
{% extends 'base.html' %}

{% block title%}
	LinsAlert - Авторизация
{% endblock %}

{% block sign_in_page %}
active
{% endblock %}

{% block content %}
<div class="container">
	<form class="form-sign" action="/sign_in/" method="post">{% csrf_token %}
		<h2 class="form-sign-heading">Авторизация</h2>
		{{ form.username }}
		{% if form.username.errors %}
			{% for error in form.username.errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		{{ form.password }}
		{% if form.password.errors %}
			{% for error in form.password.errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		{% if form.non_field_errors %}
			{% for error in form.non_field_errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}
		
		<button class="btn btn-lg btn-primary btn-block" type="sumbit">Войти</button>
		<p style="text-align: center; font-size: 24px; margin-top: 10px;">или</p>
		<a onclick="$(this).button('loading');" class="btn btn-lg btn-block btn-vk" data-loading-text="Идет авторизация..." type="button" href="https://oauth.vk.com/authorize?client_id=3848319&scope=&redirect_uri=http://linsalert.mooo.com/sign_in_vk&response_type=code"><i class="icon-vk"></i> | Войти через VK</a>		
	</form>
</div>
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html' %}

{% block title%}
	LinsAlert - Регистрация
{% endblock %}

{% block sign_up_page %}
active
{% endblock %}

{% block content %}
<div class="container">
	<form class="form-sign" action="/sign_up/" method="post">{% csrf_token %}
		<h2 class="form-sign-heading">Регистрация</h2>
		{{ form.username }}
		{% if form.username.errors %}
			{% for error in form.username.errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		{{ form.password }}
		{% if form.password.errors %}
			{% for error in form.password.errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		{{ form.password_repeat }}
		{% if form.password_repeat.errors %}
			{% for error in form.password_repeat.errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		{% if form.non_field_errors %}
			{% for error in form.non_field_errors %}
				<div class="alert alert-danger alert-dismissable">
					<strong>{{ error|escape }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				</div>
			{% endfor %}
		{% endif %}

		<button class="btn btn-lg btn-block btn-primary" type="sumbit">Зарегистрироваться</button>
		<p style="text-align: center; font-size: 24px; margin-top: 10px;">или</p>
		<a onclick="$(this).button('loading');" class="btn btn-lg btn-block btn-vk" data-loading-text="Идет авторизация..." type="button" href="https://oauth.vk.com/authorize?client_id=3848319&scope=&redirect_uri=http://linsalert.mooo.com/sign_in_vk&response_type=code"><i class="icon-vk"></i> | Войти через VK</a>		
	</form>
</div>
{% endblock %}